SUBDIRS = processor state
PROGRAMS = functions.sh main.sh
INSTALLDIR = $(FUNCTIONSDIR)

include ../makefile.inc

clean: clean-default
clean-install: clean-install-default
build: build-default
test: test-default
install: install-default
