PROGRAMS = functions.sh main.sh
SUBDIRS = processor state
BINDIR = $(FUNCTIONSDIR)

include ../makefile.inc

build: build-default
clean: clean-default
clean-install: clean-install-default
install: install-default

