SUBDIRS = cgi-bin
PROGRAMS = bash-cgi.sh cgi-svc-wrapper.sh webserver.sh
INSTALLDIR = $(RESTAPIDIR)

include ../makefile.inc

build: build-default
test: test-default
clean: clean-default
clean-install: clean-install-default
install: install-default
