SUBDIRS = cgi-bin
PROGRAMS = bash-cgi.sh cgi-svc-wrapper.sh webserver.sh
INSTALLDIR = $(RESTAPIDIR)

include ../makefile.inc

clean: clean-default
clean-install: clean-install-default
build: build-default
lint: lint-default
test: test-default
install: install-default
