#!/usr/bin/env bash
set -eu
DEBUG=1
[ "${DEBUG:-0}" = "1" ] && set -x

PROGRAM="$( basename "$SCRIPT_NAME" | tr -C -d 'a-zA-Z0-9_-' )" # sanitize CGI var
BACKEND_PATH="../../../backend/$PROGRAM.sh"
content_type="text/plain"

# Load CGI variables and functions
. "./bash.cgi"
declare -A cgi_get cgi_post
__cgi_getvars

# If PATH_INFO is '/jobs/new', run function '_cgi_${PROGRAM}_jobs_new $@'
path_info_func="$( printf "${PATH_INFO//\//_}" | tr -C -d 'a-zA-Z0-9-' )" # sanitize CGI var
if [ "$(type -t _cgi_${PROGRAM}$path_info_func)" = "function" ] ; then
    _cgi_${PROGRAM}$path_info_func "$@"
else
    __httperror 404 "Not Found"
fi
