BINDIR = $(FUNCTIONSDIR)/state
SUBDIRS = 
PROGRAMS = state.sh local.sh

include ../../makefile.inc

build: build-default
clean: clean-default
clean-install: clean-install-default
install: install-default
