SUBDIRS = 
PROGRAMS = state.sh local.sh
INSTALLDIR = $(FUNCTIONSDIR)/state

include ../../makefile.inc

clean: clean-default
clean-install: clean-install-default
build: build-default
lint: lint-default
test: test-default
install: install-default
