BINDIR = $(FUNCTIONSDIR)/state
SUBDIRS = 
PROGRAMS = state.sh local.sh

include ../../makefile.inc

clean: clean-default
clean-install: clean-install-default
build: build-default
test: test-default
install: install-default
