SUBDIRS = 
PROGRAMS = logger_pipe.sh
INSTALLDIR = $(FUNCTIONSDIR)/processor

include ../../makefile.inc

clean: clean-default
clean-install: clean-install-default
build: build-default
lint: lint-default
test: test-default
install: install-default
