BINDIR = $(FUNCTIONSDIR)/processor
SUBDIRS = 
PROGRAMS = logger_pipe.sh

include ../../makefile.inc

clean: clean-default
clean-install: clean-install-default
build: build-default
test: test-default
install: install-default
